### ISSUE TITLE
Running tests do not finish after the end inside CI

### ISSUE THREAD

**Issue by mitar** [Meteor-Community-Packages/meteor-mocha#107]
I have hard time figuring out what is happening because it happens just inside CI and not locally. But simply, after both server and client tests finish, Meteor process does not exist. See [example output here](https://gitlab.com/peer/doc/-/jobs/842631157):

```
I20201111-08:09:16.197(0)? All tests finished!
I20201111-08:09:16.198(0)? 
I20201111-08:09:16.202(0)? --------------------------------
I20201111-08:09:16.203(0)? APP SERVER FAILURES: 0
I20201111-08:09:16.204(0)? APP CLIENT FAILURES: 1
I20201111-08:09:16.204(0)? --------------------------------
ERROR: Job failed: execution took longer than 1h0m0s seconds
```

I am running it with:

```
SERVER_TEST_REPORTER=xunit XUNIT_FILE="$(pwd)/tests/reports/server-test-results.xml" TEST_BROWSER_DRIVER=chrome TEST_CHROME_ARGS='--no-sandbox --disable-dev-shm-usage' meteor test --full-app --once --driver-package meteortesting:mocha --port 3100 --settings settings.example.json
```

Not sure how to debug this. Any ideas?

**Comment by mitar** [comment]
Same even when there are [no failures](https://gitlab.com/peer/doc/-/jobs/842914204).

**Comment by dovydaskukalis** [comment]
We had the same issue and found out it's because of this [handleCoverage](https://github.com/meteortesting/meteor-mocha/blob/master/package/server.js#L79) call. It doesn't exit since process.exit() is inside promise callback (although I am not sure why). We simply removed that function call since we don't use it and it fixed it. I am not sure what proper solution would be.

**Comment by mitar** [comment]
In my case it turns out to be a problem of using fibers inside the `process.once('exit', ...)` callback. It seems [this just blocks the process](https://github.com/laverdet/node-fibers/issues/453). So nothing to do with the test runner.
