### ISSUE TITLE
Bump supported dependency versions of lmieulet:meteor-coverage to 4.0.0

### ISSUE THREAD

**Issue by bessw** [Meteor-Community-Packages/meteor-mocha#121]
Could you please bump the supported version of `lmieulet:meteor-coverage` to 4.0.0
https://github.com/Meteor-Community-Packages/meteor-mocha/blob/2053b3dc30895fd15a1edef0358ac6830de173ed/package/package.js#L18

**Comment by jankapunkt** [comment]
I am working on it, however I first need to get the tests running

**Comment by jankapunkt** [comment]
Related: https://github.com/serut/meteor-coverage/issues/85
