### ISSUE TITLE
The meteor http package is deprecated

### ISSUE THREAD

**Issue by Pakleni** [Meteor-Community-Packages/meteor-mocha#148]
In meteor [docs](https://docs.meteor.com/api/http.html) we can find that the http package is deprecated, you could switch to [jkuester:http](https://github.com/jankapunkt/meteor-http), or just straight up implement fetch.

**Comment by danopia** [comment]
It looks like meteor/http is only imported in one file: https://github.com/Meteor-Community-Packages/meteor-mocha/blob/a6c7735cf4227c813b44762c15ea66ec58a7cc7d/package/server.handleCoverage.js#L1 and the usages are very minimal, so at first glance this looks like a good candidate for switching to fetch.

**Comment by dokithonon** [comment]
Any news about upgrading from http to fetch ? Thanks

**Comment by jankapunkt** [comment]
I'm adding this to this PR #157
